spring:
  application:
    name: zuul
  rabbitmq:
    host: 192.168.35.132
    port: 5672
    username: admin
    password: admin
    
server:
  port: 3001
zuul:
  retryable: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
#zuul:
#  routes:
#    item-service: /item-service/**
#    user-service: /user-service/**
#    order-service: /order-service/**
